name: Azure App Service CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # ✅ Enables OIDC authentication
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image to Docker Hub
        run: |
          docker build -t sirvaiys/fastapi-mlops:latest .
          docker push sirvaiys/fastapi-mlops:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login (Using OpenID Connect)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "fastapi-mlops"
          images: "sirvaiys/fastapi-mlops:latest"
